# Generated by Django 4.1.1 on 2023-01-31 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='createdAt',
            field=models.DateTimeField(auto_now=True, verbose_name='Tarih'),
        ),
    ]
